-- MySQL Script generated by MySQL Workbench
-- Tue May 27 08:33:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbnota1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbnota1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbnota1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbnota1` ;

-- -----------------------------------------------------
-- Table `dbnota1`.`rol_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnota1`.`rol_usuario` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `id_rol_UNIQUE` (`id_rol` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbnota1`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnota1`.`usuario` (
  `ID_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NULL DEFAULT NULL,
  `contraseña` VARCHAR(45) NULL DEFAULT NULL,
  `id_rol` INT NULL DEFAULT NULL,
  `p.Nombre` VARCHAR(45) NULL,
  `s.Nombre` VARCHAR(45) NULL,
  `p.Apellido` VARCHAR(45) NULL,
  `s.Apellido` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` VARCHAR(12) NULL,
  PRIMARY KEY (`ID_usuario`),
  UNIQUE INDEX `ID_usuario_UNIQUE` (`ID_usuario` ASC) VISIBLE,
  INDEX `rol_usuario_idx` (`id_rol` ASC) VISIBLE,
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE,
  CONSTRAINT `rol_usuario`
    FOREIGN KEY (`id_rol`)
    REFERENCES `dbnota1`.`rol_usuario` (`id_rol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbnota1`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnota1`.`curso` (
  `ID_curso` INT NOT NULL AUTO_INCREMENT,
  `grado` VARCHAR(45) NULL DEFAULT NULL,
  `usuario_ID_usuario` INT NOT NULL,
  PRIMARY KEY (`ID_curso`),
  UNIQUE INDEX `ID_curso_UNIQUE` (`ID_curso` ASC) VISIBLE,
  INDEX `fk_curso_usuario1_idx` (`usuario_ID_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_curso_usuario1`
    FOREIGN KEY (`usuario_ID_usuario`)
    REFERENCES `dbnota1`.`usuario` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbnota1`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnota1`.`asignatura` (
  `ID_asignatura` INT NOT NULL AUTO_INCREMENT,
  `nombre_asignatura` VARCHAR(45) NULL DEFAULT NULL,
  `curso_ID_curso` INT NOT NULL,
  PRIMARY KEY (`ID_asignatura`),
  UNIQUE INDEX `ID_asignatura_UNIQUE` (`ID_asignatura` ASC) VISIBLE,
  INDEX `fk_asignatura_curso1_idx` (`curso_ID_curso` ASC) VISIBLE,
  CONSTRAINT `fk_asignatura_curso1`
    FOREIGN KEY (`curso_ID_curso`)
    REFERENCES `dbnota1`.`curso` (`ID_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbnota1`.`asignatura-docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnota1`.`asignatura-docente` (
  `ID_asig_doc` INT NOT NULL,
  `usuario_ID_usuario` INT NOT NULL,
  `asignatura_ID_asignatura` INT NOT NULL,
  PRIMARY KEY (`ID_asig_doc`),
  INDEX `fk_asignatura-docente_usuario1_idx` (`usuario_ID_usuario` ASC) VISIBLE,
  INDEX `fk_asignatura-docente_asignatura1_idx` (`asignatura_ID_asignatura` ASC) VISIBLE,
  CONSTRAINT `fk_asignatura-docente_usuario1`
    FOREIGN KEY (`usuario_ID_usuario`)
    REFERENCES `dbnota1`.`usuario` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura-docente_asignatura1`
    FOREIGN KEY (`asignatura_ID_asignatura`)
    REFERENCES `dbnota1`.`asignatura` (`ID_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbnota1`.`lista_participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnota1`.`lista_participante` (
  `ID_lista` INT NOT NULL AUTO_INCREMENT,
  `usuario_ID_usuario` INT NOT NULL,
  `ID_asig_doc` INT NOT NULL,
  PRIMARY KEY (`ID_lista`),
  UNIQUE INDEX `ID_lista_UNIQUE` (`ID_lista` ASC) VISIBLE,
  INDEX `fk_lista_participante_usuario1_idx` (`usuario_ID_usuario` ASC) VISIBLE,
  INDEX `fk_lista_participante_asignatura-docente1_idx` (`ID_asig_doc` ASC) VISIBLE,
  CONSTRAINT `fk_lista_participante_usuario1`
    FOREIGN KEY (`usuario_ID_usuario`)
    REFERENCES `dbnota1`.`usuario` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lista_participante_asignatura-docente1`
    FOREIGN KEY (`ID_asig_doc`)
    REFERENCES `dbnota1`.`asignatura-docente` (`ID_asig_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbnota1`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbnota1`.`nota` (
  `ID_nota` INT NOT NULL AUTO_INCREMENT,
  `valor_nota` INT NULL DEFAULT NULL,
  `comentarios` VARCHAR(45) NULL DEFAULT NULL,
  `lista_participante_ID_lista` INT NOT NULL,
  `curso_ID_curso` INT NOT NULL,
  PRIMARY KEY (`ID_nota`),
  UNIQUE INDEX `ID_nota_UNIQUE` (`ID_nota` ASC) VISIBLE,
  INDEX `fk_nota_lista_participante1_idx` (`lista_participante_ID_lista` ASC) VISIBLE,
  INDEX `fk_nota_curso1_idx` (`curso_ID_curso` ASC) VISIBLE,
  CONSTRAINT `fk_nota_lista_participante1`
    FOREIGN KEY (`lista_participante_ID_lista`)
    REFERENCES `dbnota1`.`lista_participante` (`ID_lista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_curso1`
    FOREIGN KEY (`curso_ID_curso`)
    REFERENCES `dbnota1`.`curso` (`ID_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
